### ISSUE TITLE
2.0.1 binary stale?

### ISSUE THREAD

**Issue by fortycalsig** [ripla/ExternalLayout#1]
I had to recompile from source to fix NoSuchMethod throw at line 41 of ExternalLayout.java:

> childComponent.setParent(this);

2.0.1 distro worked with 7.0.x, throws above exception w/ 7.1.2 unless recompiled.

**Comment by ralmeida4381** [comment]
2.0.1 distro doesn't works with 7.3. Unfortunately source doesn't compile :(

**Comment by ripla** [comment]
Check https://vaadin.com/directory#!addon/externallayout for the latest.
